apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - image: glumac/testuberapp:0.1
        name: user
        imagePullPolicy: "Always"
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-user:5433/user #previous customer
          #- name: KUMULUZEE_DATASOURCES0_USERNAME
          #  value: dbuser
          #- name: KUMULUZEE_DATASOURCES0_PASSWORD
          #  value: postgres
          #- name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
          #  value: http://etcd:2379
          #- name: KUMULUZEE_CONFIG_ETCD_HOSTS
          #  value: http://etcd:2379
        ports:
        - containerPort: 8081
          name: server
          protocol: TCP

